QT += core network
QT -= gui
TARGET = userpublicdata
TEMPLATE = app
SOURCES += main.cpp 
CONFIG += link_pkgconfig debug
PKGCONFIG += QJson
LIBS += -L../../lib -lqfacebookgraph
INCLUDEPATH += ../../src
HEADERS += userdata.h
